language: java
jdk:
  - oraclejdk7
before_install:
  # Make sure apt is up to date.
  - sudo apt-get update -qq
  # Travis is on 64bit and there will be a cryptic aapt error w/o these libs.
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
  # For native code tests, we need some additional libraries if we are in a 64-bit environment.
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes gcc-multilib > /dev/null; fi
  # Download the Android sdk and unzip.
  - wget http://dl.google.com/android/android-sdk_r23-linux.tgz
  - tar -zxf android-sdk_r23-linux.tgz
  # Set up the sdk environment.
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools
  - export PATH=${PATH}:${ANDROID_HOME}/platform-tools
  - export PATH=${PATH}:${ANDROID_HOME}/build-tools
  # Install the sdk bits we need.
  - ./scripts/travisci_install_android_sdk.sh > /dev/null
  # Download the Android NDK and setup the environment.
  - wget https://dl.google.com/android/ndk/android-ndk-r9d-linux-x86_64.tar.bz2
  - tar xf android-ndk-r9d-linux-x86_64.tar.bz2
  - export ANDROID_NDK=`pwd`/android-ndk-r9d
script:
  # Use Buck to run the tests first because its output is more
  # conducive to diagnosing failed tests than Ant's is.
  # We build with `--verbose 0` to hide the SuperConsole,
  # which does not play well for Travis.
  # Travis doesn't understand curses, so it sends us over the 10000 line limit.
  - ./bin/buck build buck --verbose 0 && ./bin/buck test --all && ant travis
