language: java
jdk:
  - oraclejdk8
env:
  - CI_ACTION=build
  - CI_ACTION=unit
  - CI_ACTION=integration
  - CI_ACTION=heavy_integration
  - CI_ACTION=ant

# Enable container-based architecture.
sudo: false

addons:
  apt:
    sources:
      # For newer gcc than precise supports out of the box.
      - ubuntu-toolchain-r-test
    packages:
      # Travis is on 64bit and there will be a cryptic aapt error w/o these libs.
      # For native code tests, we need some additional libraries if we are in a 64-bit environment.
      - libgd2-xpm
      - libc6:i386
      - libstdc++6:i386
      - zlib1g:i386
      - groovy
        # We rely on -gno-record-gcc-switches which was added in 4.7.
      - gcc-4.7
      - g++-4.7
      # Getting compile errors on javac 1.8.0_31-b13
      - oracle-java8-installer

before_install:
  - mkdir travis-cxx
  - ln -s /usr/bin/gcc-4.7 travis-cxx/gcc
  - ln -s /usr/bin/g++-4.7 travis-cxx/g++
  - export PATH=$(pwd)/travis-cxx:$PATH
  # Limit Ant's and Buck's memory usage to avoid the OOM killer.
  - export ANT_OPTS='-Xmx500m'
  - echo '-Xmx500m' > .buckjavaargs.local
  # Set up the Android environment.
  - export NDK_HOME=${HOME}/android-ndk-linux
  - ./scripts/travisci_install_android_ndk.sh
  - export ANDROID_HOME=${HOME}/android-sdk-linux
  - ./scripts/travisci_install_android_sdk.sh
  # Install go 1.5
  - eval "$(gimme 1.5)"
  - echo -e "[go]\n  root = ${GOROOT}" >> .buckconfig
  # Set up the Groovy environment
  - export GROOVY_HOME=/usr/share/groovy/

# https://docs.travis-ci.com/user/caching#Things-not-to-cache
# https://docs.travis-ci.com/user/caching#Explicitly-disabling-caching
cache:
  directories:
    - $HOME/ndk_cache
    - $HOME/sdk_cache

notification:
  slack:
    rooms:
      secure: YCVClBpmJlhoF7W/POHKGnBqzFkiY+uG8QEsre0b5AJDZlWy1CfF6JYplkieg5z7zGlnC4c7VqdCcjPtHT7aBVD5t4GmpHWo6hx9wdEm0orTV+n1MTQgjzeGIEMZO0iSEvU0pGkJC0mHeQ5HrwBHLzGaNrjQO+CkxTeu1J59cW0=

script:
  - ./scripts/travisci_run.sh
