os: Visual Studio 2015

version: '{build}'

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - cmd: choco install ant -y -f -i
  - cmd: refreshenv
  - cmd: echo -Djna.nosys=true > .buckjavaargs.local
  - cmd: set GOROOT=
  - cmd: set PATH=%PATH:C:\go\bin;=%
  - cmd: set PATH=%PATH:C:\go\bin=%
  - cmd: set ANT_OPTS=-Xmx512m
  - cmd: set
  - cmd: python --version
  - cmd: java -version
  - cmd: ant -version

# to disable automatic builds by MsBuild
build: off

build_script:
  - "ant"
  - "bin\\buck build buck"

test_script:
  - "bin\\buck test --all --test-selectors=':windows_failures.txt' --test-selectors=':windows_cxx_support.txt'"

artifacts:
  - path: buck-out\gen\programs\buck.pex
