version: 2.1

orbs:
  win: circleci/windows@2.2.0

install_openjdk8: &install_openjdk8
  name: Install OpenJDK8
  command: |
    if [ "${PLATFORM}" == "linux" ]; then
      sudo apt-get update && sudo apt-get install openjdk-8-jdk
      sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
    elif [ "${PLATFORM}" == "macos" ]; then
      brew cask install adoptopenjdk8
    fi
    java -version

install_android_sdk: &install_android_sdk
  name: Install Android SDK
  command: |
    sdk_os="linux"
    if [ "${PLATFORM}" == "macos" ]; then
      sdk_os="darwin"
    fi
    sdk_zip_filename="sdk-tools-${sdk_os}-4333796.zip"
    mkdir -p "${ANDROID_SDK}"
    cd "${ANDROID_SDK}"
    curl -O "https://dl.google.com/android/repository/${sdk_zip_filename}"
    unzip "${sdk_zip_filename}"
    export PATH="${ANDROID_SDK}/tools/bin:${PATH}"
    echo 'y' |sdkmanager --install tools
    echo 'y' |sdkmanager --install platform-tools
    echo 'y' |sdkmanager --install "build-tools;28.0.0"
    echo 'y' |sdkmanager --install "platforms;android-23"

    # Install 32 bit libraries
    # https://stackoverflow.com/questions/36911709/cannot-run-program-aapt
    # Needed to run Android build-tools
    if [ "${PLATFORM}" == "linux" ]; then
      sudo apt-get install gcc-multilib lib32z1 lib32stdc++6
    fi

install_python: &install_python
  name: Install Python 3.6.2
  command: |
    if [ "${PLATFORM}" == "macos" ]; then
      brew install pyenv
    fi
    pyenv install -s 3.6.2
    pyenv global 3.6.2 system
    export PATH="$(pyenv root)/shims:${PATH}"
    python --version

linux_environment: &linux_environment
  # Use string constant for values, no environment variables 
  PLATFORM: "linux"
  BUCKROOT: "/home/circleci/buck"
  ANDROID_SDK: "/home/circleci/android-sdk"
  TERM: "dumb"
  BUCK_NUM_THREADS: 3
  BUCK_PEX_LOCATION: "./new_buck.pex"

jobs:
  publish_docs:
    environment:
      <<: *linux_environment
    working_directory: "/home/circleci/buck"
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          <<: *install_openjdk8
      - run:
          # android_sdk needed to build java docs.
          <<: *install_android_sdk
      - run:
          <<: *install_python
      - run:
          # We do not want to build buck, install the latest release instead.
          name: Install Buck
          command: |
            url=`curl -sH "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/repos/facebook/buck/releases/latest |grep "browser_download_url.*deb" |awk '{gsub("\"", "", $2); print $2}'`
            curl -L -O $url
            filename=`basename ${url}`
            sudo dpkg -i ${filename} || echo "Warning: Buck installed without dependencies."
      - run:
          name: Publish docs
          command: |
            export ANDROID_HOME="${ANDROID_SDK}"
            cd docs
            ./publish.sh --start-soyweb

workflows:
  version: 2.1
  publish_docs_cron_job:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only: master
    jobs:
      - publish_docs
