version: 2

aliases:
  - &restore-android-sdk
    keys:
      - android-sdk-{{ checksum "scripts/android-sdk-setup.sh" }}
      - android-sdk
  - &save-android-sdk
    paths:
      - /opt/android
    key: android-sdk-{{ checksum "scripts/android-sdk-setup.sh" }}
  - &android-setup
     name: Setup Android SDK
     command: sdkmanager 'build-tools;23.0.2' 'platforms;android-23' 'platforms;android-21'  'add-ons;addon-google_apis-google-21' 'add-ons;addon-google_apis-google-23'
  - &apt-dependencies
    name: Install APT dependencies
    command: |
      sudo apt-get -qq -y update
      sudo apt install -qq -y --no-install-recommends ant gcc g++ ghc ghc-dynamic git groovy python ssh-client unzip wget
  - &run-ci-script
    name: Run CI script
    command: |
      echo '-Xmx500m' > .buckjavaargs.local
      ./scripts/travisci_run.sh

references:
  workspace_root: &workspace_root
      ~/buck
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

defaults: &defaults
   docker:
     - image: circleci/android:api-26-alpha
   working_directory: ~/buck

jobs:
  build:
    <<: *defaults
    environment:
      CI_ACTION: build

    steps:
      - run: *apt-dependencies
      - checkout
      - run: *android-setup
      - run: *run-ci-script

  unit:
    <<: *defaults
    environment:
      CI_ACTION: unit
      GROOVY_HOME: /usr/share/groovy/

    steps:
      - run: *apt-dependencies
      - checkout
      - run: *android-setup
      - run: *run-ci-script

  integration:
    <<: *defaults
    environment:
      CI_ACTION: integration
      GROOVY_HOME: /usr/share/groovy/

    steps:
      - run: *apt-dependencies
      - checkout
      - run: *android-setup
      - run: *run-ci-script

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unit:
          requires:
            - build
      - integration:
          requires:
            - build
